# Generated by Django 5.0.4 on 2024-06-13 00:26

import configs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', configs.models.EncryptedTextField()),
                ('expires_in', models.IntegerField()),
                ('refresh_token', configs.models.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discord_auth_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configs.discordauthtoken')),
            ],
        ),
    ]
