# Generated by Django 5.0.4 on 2024-06-13 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_remove_config_id_alter_config_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='discord_auth_token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.discordauthtoken'),
        ),
    ]
