# Generated by Django 5.0.4 on 2024-06-21 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_alter_config_discord_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='discord_auth_token',
        ),
        migrations.AddField(
            model_name='discordauthtoken',
            name='config',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='configs.config'),
        ),
    ]
