# Generated by Django 5.0.4 on 2024-06-21 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_remove_config_discord_auth_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordauthtoken',
            name='id',
        ),
        migrations.AlterField(
            model_name='discordauthtoken',
            name='config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='configs.config'),
        ),
    ]
