# Generated by Django 5.0.4 on 2024-07-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_remove_discordauthtoken_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordauthtoken',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='discordauthtoken',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
