# Generated by Django 5.0.4 on 2024-07-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0007_config_discord_id_delete_discordauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='discord_id',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
