# Generated by Django 5.0.4 on 2024-09-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0009_config_discord_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='discord_id',
            field=models.PositiveBigIntegerField(blank=True, default=0, unique=True),
        ),
    ]
